### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [awallner-WallE/RasterMCDA-QGIS_Plugin#1]
Please remove https://github.com/awallner-WallE/RasterMCDA-QGIS_Plugin/tree/main/raster_mcda/__pycache__ and any .pyc files. They are autogenerated on install.

Also, update the plugin repo with the latest zip

**Comment by awallner-WallE** [comment]
Thank you for your reply,
edits have been made and QGIS Plugin repository-zip is also updated.
Hope now everything is ok
