### ISSUE TITLE
when is the OWA due?

### ISSUE THREAD

**Issue by mzecast** [awallner-WallE/RasterMCDA-QGIS_Plugin#2]
Your plugin is working fine, thanks. When are we going to get the OWA part of it? It would be very nice and useful for my classes, and count me if you need feedback.

**Comment by awallner-WallE** [comment]
Hey, thanks for the first feedback!

OWA should be already available within the OWA tab (see screenshot)

![grafik](https://user-images.githubusercontent.com/79254477/112293758-c5686880-8c92-11eb-9db8-3c30c03cbe60.png)

Here you can add relevant criteria, weights and the ordered weights.

I will also write a short description of the different decision rules and upload it to GitHub soon.

Feedback is always welcome! I am relatively new to the Plugin development stuff ;)

**Comment by mzecast** [comment]
Sorry, and yes, you are right, I couldn't access it because I hadn't indicated the factors.

However, is there something wrong with these cases?
![Wallner02](https://user-images.githubusercontent.com/80954016/112310078-0dd85400-8c9c-11eb-8393-11280987e8ac.jpg)
![Wallner01](https://user-images.githubusercontent.com/80954016/112310082-0f098100-8c9c-11eb-944d-38ec0ed95966.jpg)

And thanks a lot again!

**Comment by awallner-WallE** [comment]
Hey, 
Ok, there seems to be a little bug because your input looks ok.
I will observe that and come back to you!

**Comment by awallner-WallE** [comment]
OK! 
The problem should be solved now; 
I uploaded the newest version of the Plugin on the QGIS Plugin Repository. You can upgrade it after the new version is approved. Alternatively, you can download it from GitHub and install it as a zip. (Also the GUI should look better now)

Note that the implemented OWA function is very time consuming for the PC, it might be possible that your QGIS gets stuck for some minutes while it's calculating.

Thanks for locating the error and using the Plugin!

**Comment by mzecast** [comment]
Hello,
I had closed the issue, but the problem with OWA weightings remains. The zip installer indicates that the metadata file is missing, and in the plugin manager, it indicates a new version, but after installing, the new version message is still there.
I want help; this plugin would be very much of interest to me.
Thank you.

**Comment by awallner-WallE** [comment]
Hey, I am sorry that you came into that trouble...

are you sure you use the right version now? 
I installed the Plugin (via the Plugin Manager) on a different computer now and the error didnt occure
![20210330_105102.jpg](https://user-images.githubusercontent.com/79254477/112961786-fb4f9600-9145-11eb-9941-255e89727205.jpg)

Maybe try to deinstall the Plugin and install again The installed version should be 1.02 (vissible in Plugin Manager)
![20210330_105039.jpg](https://user-images.githubusercontent.com/79254477/112961807-ff7bb380-9145-11eb-8cfc-095119f35bc8.jpg)

(Sorry for bad img quality)
