### ISSUE TITLE
plugin installation error

### ISSUE THREAD

**Issue by felxcon** [awallner-WallE/RasterMCDA-QGIS_Plugin#3]
Dear awallner,
I am looking forward to use your plugin RasterMCDA :). However, it appears that there might be compatibility problems with QGIS v3.20 onwards (Win10). I get the following >ModuleNotFoundError: No module named 'osr'< when trying to install RasterMCDA. I tried several older versions of QGIS for installing the plugin and found no errors for QGIS versions 3.4.15 til 3.18.3 (=it works in QGIS v3.4.15 to v3.18.3). This issue not only arises for your Plugin RasterMCDA but also WMCA (https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA).

**Comment by awallner-WallE** [comment]
Hey, thank you for the information! 
When I have some time left I try to look into it and respond when there is a solution.

MFG WA

**Comment by DanielAkizune** [comment]
hola tengo dudas si este plugin podría mejorar y el como, o que características nuevas podría agregarse o corregirse. saludos

**Comment by awallner-WallE** [comment]
Hey, sorry that the Plugin is not maintained by me at the moment.
At the moment, I am in the final phase of my study and do not find the extra time to work on this…

MFG WA

**Comment by bellanz80** [comment]
Apparently just by changing "import osr" to "from osgeo import osr", it works perfectly in QGIS 3.26!
In the line 45 of raster_MCDA.py
Taken the same idea from another plug

https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA/issues/10

**Comment by awallner-WallE** [comment]
Should now work thanks to @ecodiv, Thanks!
